# -*- coding: utf-8 -*-
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

CarModel.create(description:  'Maximaler Raum auf minimaler Fläche: Der up! überrascht als vollwertiger Viersitzer mit einem in seiner Klasse ungewöhnlichen Platzangebot. Intelligente Detail-Lösungen und das klar gestaltete Interieur überzeugen ebenso wie die kompromisslose Sicherheit eines Großen.', price:  '9850', name:  'Der neue up!')
CarModel.create(description:  'Sie sind ein echter Individualist, mit eigenen Vorstellungen und einer Meinung, für die Sie sich auch einsetzen? Dann ist der Polo der richtige Begleiter für Sie! Markant, kraftvoll und auffallend eigenständig im Design bezieht er ganz klar Stellung: Ihre.', price:  '12450', name:  'Der Polo')
CarModel.create(description:  'Der Golf ist nicht nur der leiseste, den es je gab. Er ist auch der hochwertigste Golf aller Zeiten. Mit seinem durch klare Linen geprägten, sportlichen Design, dem überzeugenden Innenraumkonzept und seinen innovativen Motorisierungen legt er einen fulminanten Start hin.', price:  '16975', name:  'Der Golf')
CarModel.create(description:  'Zeitgemäße Mobilität: Der Golf ist DAS AUTO. Serienmäßig mit BlueMotion Technology, Multikollisionsbremse und zahlreichen weiteren Innovationen ausgestattet, besticht er ebenfalls durch attraktive Proportionen und hochwertiges Interieur.', price:  '16975', name:  'Der neue Golf')
CarModel.create(description:  '1.580 mm Höhe. 1.450 l Stauraum. Und jede Menge Ablagefächer. Der Golf Plus bietet Ihnen jetzt noch mehr Raum, um sich frei zu entfalten.', price:  '18775', name:  'Der Golf Plus')
CarModel.create(description:  'Der Golf Variant gibt Anlass zu großen Erwartungen. Und er erfüllt sie spielend: Neben seinem imposanten Stil beweist er durch seinen beträchtlichen Stauraum – von bis zu 1.495 Litern – wahre Größe.', price:  '18950', name:  'Der Golf Variant')
CarModel.create(description:  'Immer der Sonne entgegen: Im Golf Cabriolet steht Ihnen die Welt offen. Das vollautomatische descriptionilverdeck mit integrierter Glas-Heckscheibe lässt sich in Sekundenschnelle dem Wetter anpassen.', price:  '23625', name:  'Das Golf Cabriolet')
CarModel.create(description:  'Stolz auf ein einzigartiges Erbe, doch den Blick nach vorn gerichtet: Der Beetle ist unverwechselbar wie der legendäre Käfer und strahlt Dynamik und Selbstbewusstsein aus: mit markantem Design, innovativem Infotainment und kompromissloser Qualität.', price:  '16950', name:  'The Beetle')
CarModel.create(description:  'Charismatische Frontpartie, grandiose Performance und gefährlich schöne Kurven – dem Scirocco ist einfach schwer zu widerstehen. Eine seiner Stärken: die komfortable Sportsitzanlage für Fahrer und Beifahrer. So sieht kompromisslose Sportlichkeit aus.', price:  '22825', name:  'Der Scirocco')
CarModel.create(description:  'Noch mehr Eleganz. Noch mehr Sportlichkeit. Noch mehr Komfort. Der Jetta bietet einfach mehr.', price:  '21200', name:  'Der Jetta')
CarModel.create(description:  'Ein vernünftiges Auto kann so gut aussehen: Der Touran überzeugt mit durchdachter Funktionalität und modernem Design.', price:  '21975', name:  'Der Touran')
CarModel.create(description:  'Der Tiguan beeindruckt gleich doppelt mit markantem Design: Als einziger SUV seiner Klasse bietet er die Wahl zwischen einer Onroad- und einer Offroad-Version. Für Fahrspaß auf der Straße und im Gelände sorgen effiziente Motoren und die komfortable Ausstattung.', price:  '24175', name:  'Der Tiguan')
CarModel.create(description:  'Die Zeiten, in denen Sie sich zwischen einem Cabrio und einem Coupé entscheiden mussten, sind vorbei.<br>Der Eos bietet Ihnen das Beste aus zwei Welten: Authentischer, sportiver Cabriogenuss und der dynamische Auftritt eines klassischen Coupés.', price:  '28375', name:  'Der Eos')
CarModel.create(description:  'Oberklasse-Flair in der Mittelklasse: Das eigenständige Design des Passat wirkt hochwertiger denn je, und zahlreiche gute Ideen bei Komfort- und Sicherheitsausstattungen bestätigen diesen Eindruck.', price:  '24775', name:  'Der Passat')
CarModel.create(description:  'Oberklasse-Flair in der Mittelklasse: Das eigenständige Design des Passat wirkt hochwertiger denn je, und zahlreiche gute Ideen bei Komfort- und Sicherheitsausstattungen bestätigen diesen Eindruck.', price:  '25800', name:  'Der Passat Variant')
CarModel.create(description:  'Komfort, Sicherheit und Authentizität: Der Passat Alltrack bietet durchdachte Wertigkeit in jedem Ausstattungsdetail, wie z. B. dem serienmäßigen Offroad-Fahrprogramm mit Berganfahr- und Bergabfahrassistent – für komfortablen Fahrspaß auch abseits des Asphalts.', price:  '33450', name:  'Der neue Passat Alltrack')
CarModel.create(description:  'Er verführt mit dem Charme eines sportlichen Coupés und verlockt mit der Vernunft einer klassischen Limousine: Der neue Volkswagen CC vereint scheinbare Gegensätze auf besonders schöne Weise.', price:  '31800', name:  'Der neue Volkswagen CC')
CarModel.create(description:  'Mehr Spielraum: Das intelligent durchdachte Raumkonzept des Sharan überzeugt durch Flexibilität, erfreut durch Komfort und begeistert durch Eleganz.', price:  '29800', name:  'Der Sharan')
CarModel.create(description:  'Das markante, unverwechselbare Design des Touareg weckt hohe Erwartungen. Seine komfortable Ausstattung, seine technischen Innovationen und seine Verbrauchswerte übertreffen sie.', price:  '49625', name:  'Der Touareg')
CarModel.create(description:  'Expressive Eleganz, sinnvolle Technologie und ein überlegenes Komforterlebnis: Der Phaeton bietet Genuss in Manufakturqualität.', price:  '68325', name:  'Der Phaeton')
CarModel.create(description:  'Die Großraumlimousine mit viel Platz und umfassender Ausstattung.<br><br>Ob mit der Familie, beim Sport oder für die Urlaubsfahrt: Der Caddy lässt sich in vielfältiger Weise nutzen. Er bietet Platz für bis zu sieben Personen und der Caddy Maxi dazu noch reichlich Raum für Ihr Gepäck.', price:  '', name:  'Der Caddy')
CarModel.create(description:  'Das komfortable Reisemobil mit vier Schlafplätzen.<br><br>Der Innenraum des California ist flexibel. Er bietet nicht nur Platz für Ausrüstung und Gepäck, sondern dank des Aufstelldachs auch insgesamt vier Schlafplätze. Erhältlich ist er als California Beach und als California Comfortline.', price:  '', name:  'Der California')
CarModel.create(description:  'Flexibler Innenraum. Und eine Vielzahl an Ausstattungen.<br><br>Vom Startline über den Comfortline und Highline bis zum PanAmericana: Der Multivan ist eine enorm vielseitige Großraumlimousine. Allen Varianten gemeinsam: der variable Innenraum mit bis zu acht Sitzplätzen.', price:  '', name:  'Der Multivan')
CarModel.create(description:  'Nutzfahrzeuge von Volkswagen arbeiten zuverlässig, sind robust, langlebig und wirtschaftlich. Ob große und kleine Lasten oder Personenbeförderung: Der Caddy® und der Caddy Maxi, der Transporter, der Caravelle, der Crafter und der Amarok werden mit nahezu jeder Aufgabe fertig.', price:  '', name:  'Volkswagen Nutzfahrzeuge')