# -*- coding: utf-8 -*-
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)



CarModel.create(description:  'Maximaler Raum auf minimaler Fläche: Der up! überrascht als vollwertiger Viersitzer mit einem in seiner Klasse ungewöhnlichen Platzangebot. Intelligente Detail-Lösungen und das klar gestaltete Interieur überzeugen ebenso wie die kompromisslose Sicherheit eines Großen.', price:  '9850', name:  'Der neue up!', image: '/attaches/models/6db9b236_410_169.png')
CarModel.create(description:  'Sie sind ein echter Individualist, mit eigenen Vorstellungen und einer Meinung, für die Sie sich auch einsetzen? Dann ist der Polo der richtige Begleiter für Sie! Markant, kraftvoll und auffallend eigenständig im Design bezieht er ganz klar Stellung: Ihre.', price:  '12450', name:  'Der Polo', image: '/attaches/models/bd286e5a_410_169.png')
# CarModel.create(description:  'Der Golf ist nicht nur der leiseste, den es je gab. Er ist auch der hochwertigste Golf aller Zeiten. Mit seinem durch klare Linen geprägten, sportlichen Design, dem überzeugenden Innenraumkonzept und seinen innovativen Motorisierungen legt er einen fulminanten Start hin.', price:  '16975', name:  'Der Golf', image: '')
CarModel.create(description:  'Zeitgemäße Mobilität: Der Golf ist DAS AUTO. Serienmäßig mit BlueMotion Technology, Multikollisionsbremse und zahlreichen weiteren Innovationen ausgestattet, besticht er ebenfalls durch attraktive Proportionen und hochwertiges Interieur.', price:  '16975', name:  'Der neue Golf', image: '/attaches/models/9c357e97_410_164.png')
CarModel.create(description:  '1.580 mm Höhe. 1.450 l Stauraum. Und jede Menge Ablagefächer. Der Golf Plus bietet Ihnen jetzt noch mehr Raum, um sich frei zu entfalten.', price:  '18775', name:  'Der Golf Plus', image: '/attaches/models/cfb7a0af_410_169.png')
CarModel.create(description:  'Der Golf Variant gibt Anlass zu großen Erwartungen. Und er erfüllt sie spielend: Neben seinem imposanten Stil beweist er durch seinen beträchtlichen Stauraum – von bis zu 1.495 Litern – wahre Größe.', price:  '18950', name:  'Der Golf Variant', image: '/attaches/models/b3f5b82a_410_169.png')
CarModel.create(description:  'Immer der Sonne entgegen: Im Golf Cabriolet steht Ihnen die Welt offen. Das vollautomatische descriptionilverdeck mit integrierter Glas-Heckscheibe lässt sich in Sekundenschnelle dem Wetter anpassen.', price:  '23625', name:  'Das Golf Cabriolet', image: '/attaches/models/c2330f01_410_169.png')
CarModel.create(description:  'Stolz auf ein einzigartiges Erbe, doch den Blick nach vorn gerichtet: Der Beetle ist unverwechselbar wie der legendäre Käfer und strahlt Dynamik und Selbstbewusstsein aus: mit markantem Design, innovativem Infotainment und kompromissloser Qualität.', price:  '16950', name:  'The Beetle', image: '/attaches/models/1c4d2291_410_169.png')
CarModel.create(description:  'Charismatische Frontpartie, grandiose Performance und gefährlich schöne Kurven – dem Scirocco ist einfach schwer zu widerstehen. Eine seiner Stärken: die komfortable Sportsitzanlage für Fahrer und Beifahrer. So sieht kompromisslose Sportlichkeit aus.', price:  '22825', name:  'Der Scirocco', image: '/attaches/models/16bcd4a5_410_169.png')
CarModel.create(description:  'Noch mehr Eleganz. Noch mehr Sportlichkeit. Noch mehr Komfort. Der Jetta bietet einfach mehr.', price:  '21200', name:  'Der Jetta', image: '/attaches/models/c72ec6c_410_169.png')
CarModel.create(description:  'Ein vernünftiges Auto kann so gut aussehen: Der Touran überzeugt mit durchdachter Funktionalität und modernem Design.', price:  '21975', name:  'Der Touran', image: '/attaches/models/c534cc37_410_169.png')
CarModel.create(description:  'Der Tiguan beeindruckt gleich doppelt mit markantem Design: Als einziger SUV seiner Klasse bietet er die Wahl zwischen einer Onroad- und einer Offroad-Version. Für Fahrspaß auf der Straße und im Gelände sorgen effiziente Motoren und die komfortable Ausstattung.', price:  '24175', name:  'Der Tiguan', image: '/attaches/models/9d7bff40_410_169.png')
CarModel.create(description:  'Die Zeiten, in denen Sie sich zwischen einem Cabrio und einem Coupé entscheiden mussten, sind vorbei.<br>Der Eos bietet Ihnen das Beste aus zwei Welten: Authentischer, sportiver Cabriogenuss und der dynamische Auftritt eines klassischen Coupés.', price:  '28375', name:  'Der Eos', image: '/attaches/models/e8a84700_410_169.png')
CarModel.create(description:  'Oberklasse-Flair in der Mittelklasse: Das eigenständige Design des Passat wirkt hochwertiger denn je, und zahlreiche gute Ideen bei Komfort- und Sicherheitsausstattungen bestätigen diesen Eindruck.', price:  '24775', name:  'Der Passat', image: '/attaches/models/1eb2c68_410_169.png')
CarModel.create(description:  'Oberklasse-Flair in der Mittelklasse: Das eigenständige Design des Passat wirkt hochwertiger denn je, und zahlreiche gute Ideen bei Komfort- und Sicherheitsausstattungen bestätigen diesen Eindruck.', price:  '25800', name:  'Der Passat Variant', image: '/attaches/models/47405e40_410_169.png')
CarModel.create(description:  'Komfort, Sicherheit und Authentizität: Der Passat Alltrack bietet durchdachte Wertigkeit in jedem Ausstattungsdetail, wie z. B. dem serienmäßigen Offroad-Fahrprogramm mit Berganfahr- und Bergabfahrassistent – für komfortablen Fahrspaß auch abseits des Asphalts.', price:  '33450', name:  'Der neue Passat Alltrack', image: '/attaches/models/24f93705_410_169.png')
CarModel.create(description:  'Er verführt mit dem Charme eines sportlichen Coupés und verlockt mit der Vernunft einer klassischen Limousine: Der neue Volkswagen CC vereint scheinbare Gegensätze auf besonders schöne Weise.', price:  '31800', name:  'Der neue Volkswagen CC', image: '/attaches/models/3bd04b53_410_169.png')
CarModel.create(description:  'Mehr Spielraum: Das intelligent durchdachte Raumkonzept des Sharan überzeugt durch Flexibilität, erfreut durch Komfort und begeistert durch Eleganz.', price:  '29800', name:  'Der Sharan', image: '/attaches/models/32ccefb8_410_169.png')
car_model = CarModel.create(description:  'Das markante, unverwechselbare Design des Touareg weckt hohe Erwartungen. Seine komfortable Ausstattung, seine technischen Innovationen und seine Verbrauchswerte übertreffen sie.', price:  '49625', name:  'Der Touareg', image: '/attaches/models/471f56e_410_169.png')
car_group = CarGroup.create(name: 'Der Touareg', car_model: car_model)
CarTrim.create(description:  'Effizienz: Das bedeutet starke Leistung bei geringem Verbrauch. Der Touareg V6 FSI mit BlueMotion Technology bringt 206 kW (280 PS) auf die Straße – bei einem kombinierten Verbrauch von 9,0 l/100 km und einer CO2-Emission von 236 g/km. (Kraftstoffverbrauch innerorts, l/100 km: 13,2 / außerorts: 8,0 / kombiniert: 9,9; CO2-Emission, g/km: 236; Effizienzklasse: E)', name: 'V6 BlueMotion Technology', price: '51275', image: 'http://cc5.volkswagen.de/cc5/images/render.ashx?type=cl&cl=33900%3aV6BlueMotionTechnology&rt=Front&rs=Large&width=425&height=235&mi=images%2fde-4.0%2fmissing_big_stage_large.gif', car_group: car_group)
CarTrim.create(description:  'Mehr Effizienz, weniger CO2-Ausstoß: Der Touareg V6 TDI BlueMotion Technology, wahlweise mit 150 kW (204 PS) oder 180 kW (245 PS) erhältlich, beeindruckt durch innovatives Motormanagement. (Kraftstoffverbrauch innerorts, l/100 km: 8,2 / außerorts: 6,3 / kombiniert: 7,0; CO2-Emission, g/km: 184; Effizienzklasse: B)', name: 'V6 TDI BlueMotion Technology', price: '49625', image: 'http://cc5.volkswagen.de/cc5/images/render.ashx?type=cl&cl=33900%3aV6TDIBlueMotionTechnology&rt=Front&rs=Large&width=425&height=235&mi=images%2fde-4.0%2fmissing_big_stage_large.gif', car_group: car_group)
CarTrim.create(description:  'In besonders anspruchsvollem Gelände unterstützt Sie z. B. das Zentraldifferenzial mit elektrisch geregelter Lamellensperre und Geländeuntersetzung sowie der permanente Allradantrieb 4XMOTION. (Kraftstoffverbrauch innerorts: 8,5 l/100 km, außerorts: 6,6 l/100 km; kombiniert: 7,3 l/100 km; CO2-Emission: 193 g/km; Effizienzklasse: C)', name: 'V6 TDI BlueMotion Tech. "Terrain Tech"', price: '54325', image: 'http://cc5.volkswagen.de/cc5/images/render.ashx?type=cl&cl=33900%3aV6TDIBlueMotionTechTerrainTech&rt=Front&rs=Large&width=425&height=235&mi=images%2fde-4.0%2fmissing_big_stage_large.gif', car_group: car_group)
CarTrim.create(description:  'Auf den ersten Blick lassen die 18-Zoll-Leichtmetallräder "Tacora" ahnen, welche Kraft im 4,2 l V8 TDI mit 250 kW (340 PS) steckt. Innen gibt der Touareg V8 TDI sich nobel: Dekoreinlagen in Nussbaum-Wurzelholz, Multifunktions-Lederlenkrad und vieles mehr. (Kraftstoffverbrauch innerorts, l/100 km: 11,9 / außerorts: 7,4 / kombiniert: 9,1; CO2-Emission, g/km: 239; Effizienzklasse: D)', name: 'V8 TDI', price: '79800', image: 'http://cc5.volkswagen.de/cc5/images/render.ashx?type=cl&cl=33900%3aV8TDI&rt=Front&rs=Large&width=425&height=235&mi=images%2fde-4.0%2fmissing_big_stage_large.gif', car_group: car_group)
car_group = CarGroup.create(name: 'Der Touareg Hybrid', car_model: car_model);
CarTrim.create(description:  'Der Touareg V6 TSI Hybrid Noch mehr Effizienz, noch weniger CO2-Ausstoß: Der Touareg V6 TSI Hybrid mit 245 kW (333 PS) ermöglicht streckenweise emissionsfreies Fahren durch die Kombination von TSI- und einem Elektromotor. (Kraftstoffverbrauch innerorts, l/100 km: 8,7 / außerorts: 7,9/ kombiniert: 8,2; CO2-Emission, g/km: 193; Effizienzklasse: B)', name: 'V8 TDI', price: '75525', image: 'http://cc5.volkswagen.de/cc5/images/render.ashx?type=cl&cl=33910%3aHybrid&rt=Front&rs=Large&width=425&height=235&mi=images%2fde-4.0%2fmissing_big_stage_large.gif', car_group: car_group)
CarModel.create(description:  'Expressive Eleganz, sinnvolle Technologie und ein überlegenes Komforterlebnis: Der Phaeton bietet Genuss in Manufakturqualität.', price:  '68325', name:  'Der Phaeton', image: '/attaches/models/471f56e_410_169.png')
CarModel.create(description:  'Die Großraumlimousine mit viel Platz und umfassender Ausstattung.<br><br>Ob mit der Familie, beim Sport oder für die Urlaubsfahrt: Der Caddy lässt sich in vielfältiger Weise nutzen. Er bietet Platz für bis zu sieben Personen und der Caddy Maxi dazu noch reichlich Raum für Ihr Gepäck.', price:  '', name:  'Der Caddy', image: '/attaches/models/e43ea131_410_169.png')
CarModel.create(description:  'Das komfortable Reisemobil mit vier Schlafplätzen.<br><br>Der Innenraum des California ist flexibel. Er bietet nicht nur Platz für Ausrüstung und Gepäck, sondern dank des Aufstelldachs auch insgesamt vier Schlafplätze. Erhältlich ist er als California Beach und als California Comfortline.', price:  '', name:  'Der California', image: '/attaches/models/7b229c21_425_175.png')
CarModel.create(description:  'Flexibler Innenraum. Und eine Vielzahl an Ausstattungen.<br><br>Vom Startline über den Comfortline und Highline bis zum PanAmericana: Der Multivan ist eine enorm vielseitige Großraumlimousine. Allen Varianten gemeinsam: der variable Innenraum mit bis zu acht Sitzplätzen.', price:  '', name:  'Der Multivan', image: '/attaches/models/538da4dd_410_169.png')
CarModel.create(description:  'Nutzfahrzeuge von Volkswagen arbeiten zuverlässig, sind robust, langlebig und wirtschaftlich. Ob große und kleine Lasten oder Personenbeförderung: Der Caddy® und der Caddy Maxi, der Transporter, der Caravelle, der Crafter und der Amarok werden mit nahezu jeder Aufgabe fertig.', price:  '', name:  'Volkswagen Nutzfahrzeuge', image: '/attaches/models/c4c48fce_410_169.png')